version: "3.9"

services:
  app:
    build: .
    container_name: instashare-app
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./uploads:/app/uploads   # persist uploads
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: instashare-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: instashare
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: instashare-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:

